### PR TITLE
Enable testing and set become: True in the become rally user tasks

### PR DESCRIPTION
**Pull request by martbhell**
- enables testing of this role against both Ubuntu and CentOS 7
 - normalize yaml format
 - install some more dependencies that the install script wanted
 - to make the cleanup task also work with ansible 2.5 and CentOS 7 and connection=local we need to set "become: True" on the tasks where we do become_user: rally. 
 - only cleanup if the install script succeeded
 - align conditional for setting swift reseller role lineinefile with the one in the ansible defaults/

Error message seen without the become: True was:

<pre>
TASK [ansible-role-rally : Clean up]
*******************************************
Friday 13 April 2018  11:31:23 +0000 (0:02:33.782)       0:02:50.291
**********
An exception occurred during task execution. To see the full traceback,
use -vvv. The error was: AttributeError: 'Connection' object has no
attribute 'supports_persistence'
fatal: [localhost]: FAILED! => {"msg": "Unexpected failure during module
execution.", "stdout": ""}
</pre>

### CODE REVIEW

**Comment by khappone** [comment]
This would need a rebase before continuing.

**Comment by martbhell** [comment]
rebased and had some conflict management :)
Let's see how it goes.

**Comment by martbhell** [comment]
Would you like me to squash this too?

**Comment by khappone** [comment]
Nah, it's fine.

**Pull request merged**
